.devops/deploy-pipelines.yml
=> fix_pipeline

.devops/deploy-pipelines.yml
Fix UAT deploy namespace
Fix UAT deploy namespace
expected)
=> fix: deploy namespace

helm/values-uat.yaml
Fix uat logging level value from none to off
Fix uat logging level value from none to off
expected)
=> fix: logging value

.devops/azure-templates/gradle-github-release.yml
Fix release task explicitating the gradle task to be executed for version increment
Fix release task explicitating the gradle task to be executed for version increment
expected)
=> fix: release task

.devops/azure-templates/gradle-github-release.yml
add jdk install step
add jdk install step
expected)
=> fix: add jdk install step

.devops/azure-templates/gradle-github-release.yml
Remove snapshot from version
Remove snapshot from version
Local command execution
expected)
=> fix: remove snapshot version

.devops/deploy-pipelines.yml
Fix UAT blue api test env file name
Fix UAT blue api test env file name
expected)
=> fix: blue api test

.github/auto_assign.yml, .github/workflows/check_pr.yml
=> feat: add check pr github action

README.md, docker-compose.yml
- Add env variables list to README file
- Fix docker compose container name
Project documentation
Local docker compose
expected)
=> fix: add env variables to README + fix docker compose

build.gradle.kts, docker-compose.yml, src/main/kotlin/it/pagopa/aca/client/GpdClient.kt, src/main/kotlin/it/pagopa/aca/config/WebClientConfig.kt, src/test/kotlin/it/pagopa/aca/client/GdpClientTest.kt, src/test/kotlin/it/pagopa/aca/config/WebClientConfigTest.kt
The client to make the invalidate position call to gpd has been added: 🚀
>  **POST** /organizations/{organizationfiscalcode}/debtpositions/{iupd}/invalidate
We have currently generated another client as the APIs are exposed under two different tags:
👉🏻 [Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/pagopa/pagopa-infra/main/src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl)
The branch from which we generate the gpd code is provisional as a PR is opened with a fix on the openapi syntax.
🔨 https://github.com/pagopa/pagopa-infra/pull/1057 ✅
The change was made to be able to make the call to invalidate a debt position
expected)
=> Feat(client) added invalidate method into client

README.md, mock/json-server/api-config/README.md, mock/json-server/api-config/src/middleware.js, mock/json-server/gpd/README.md, mock/json-server/gpd/src/db.json, mock/json-server/gpd/src/middleware.js, mock/json-server/gpd/src/routes.json
Expand api config and gpd mocks adding cases for test all possible error codes returned by the mocked api's such as 400, 409, 500
Those modifications are needed to perform test against error responses
Local test invoking mock api's with postman
expected)
=> Add error responses to mock

mock/json-server/api-config/README.md, mock/json-server/api-config/src/db.json, mock/json-server/api-config/src/middleware.js, mock/json-server/gpd/README.md, mock/json-server/gpd/src/db.json, mock/json-server/gpd/src/middleware.js
Add mock responses to handle debit position flow.
Using fiscal code 666 get debit position will return 404 and subsequent debit position creation call will return 201 with body
Those modifications are needed to perform test on debit position creation
Local test performing mock endpoint calls
expected)
=> feat(mock): add mock for creation flow

build.gradle.kts, mock/json-server/gpd/src/db.json, src/main/kotlin/it/pagopa/aca/config/WebClientConfig.kt, src/main/kotlin/it/pagopa/aca/utils/AcaUtils.kt, src/test/kotlin/it/pagopa/aca/AcaTestUtils.kt
Modified the GPD code generation to handle LocalDateTIme instead of the OffsetDateTIme as GPD does not handle the timezone currently.
The change was made to allow the management of dates returned by GPD.
The tests were performed in the DEV environment.
expected)
=> fix(gpd generation): changed OffsetDateTime to LocalDateTime

api-spec/aca-api.yaml, api-tests/ACA-api.tests.localhost.json, api-tests/env/ACA_localhost_env.json, src/main/kotlin/it/pagopa/aca/client/GpdClient.kt, src/main/kotlin/it/pagopa/aca/client/IbansClient.kt, src/main/kotlin/it/pagopa/aca/exceptions/GpdException.kt, src/test/kotlin/it/pagopa/aca/client/GdpClientTest.kt, src/test/kotlin/it/pagopa/aca/client/IbansClientTest.kt
Added validation on openapi fields. 
The change was made to check the values ​​received as input.
expected)
=> fix(openapi) added constraint validation into api-spec

gradle/wrapper/gradle-wrapper.properties
Change gradle distribution url
Change gradle distribution url
expected)
=> fix(build): fix gradle wrapper distribution url

Dockerfile, helm/values-dev.yaml, helm/values-uat.yaml
* add OpenTelemetry monitoring agent
expected)
Depends on pagopa/pagopa-infra#1146
Depends on pagopa/pagopa-azure-devops#230
=> [CHK-1590] feat(monitoring): add OpenTelemetry monitoring agent

api-spec/aca-api.yaml, helm/values-dev.yaml
👉🏻 entityFiscalCode minLength from 16 to 2
👉🏻 AmountEuroCents maximum from 99999999 to 99999999999
Modified validation check on openapi
expected)
=> CHK-2072 fix: openapi 

.devops/deploy-pipelines.yml, helm/values-prod.yaml, helm/values-uat.yaml
Added stage into deploy pipeline for PROD env.
Added helm value file for PROD env.
The change was made to provide for release in PROD of ACA.
expected)
=> feat: CHK-2059 configuration for PROD env

build.gradle.kts
Fix api config yaml spec uri ref
Fix api config yaml spec uri ref
expected)
=> fix(build): fix api config url ref

helm/values-prod.yaml
- set minReplica to 3 for prod env, one for availability zone;
- add antiPodAffinity with[ topology.kubernetes.io/zone](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone);
The goal of this PR is to increase the availability  by deploying at least one pod per availability zone.
=> feat: add antipodaffinity

api-spec/aca-api.yaml, api-tests/ACA-api.tests.json, api-tests/ACA-api.tests.localhost.json, src/main/kotlin/it/pagopa/aca/client/GpdClient.kt, src/main/kotlin/it/pagopa/aca/controllers/AcaController.kt, src/main/kotlin/it/pagopa/aca/services/AcaService.kt, src/main/kotlin/it/pagopa/aca/utils/AcaUtils.kt, src/main/kotlin/it/pagopa/aca/warmup/utils/WarmupRequests.kt, src/test/kotlin/it/pagopa/aca/AcaTestUtils.kt, src/test/kotlin/it/pagopa/aca/client/GdpClientTest.kt, src/test/kotlin/it/pagopa/aca/controller/AcaControllerTests.kt, src/test/kotlin/it/pagopa/aca/service/AcaServiceTests.kt, src/test/kotlin/it/pagopa/aca/utils/AcaUtilsTests.kt
- Add following optional new params: `nav`, `switchToExpired`, `iban`, `postalIban`
- Add new business logic
**AS IS**
the service always executes a call to `api-config` to retrieve the iban
**TO BE** (with this PR)
if any of the inputs `iban` or `postalIban` are given, the call to api-config is not executed so `iban` and `postalIban` are used
expected)
=> [PAGOPA-1711] feat: Add new input fields

helm/values-prod.yaml, helm/values-uat.yaml
=> [PAGOPA-2117] fix: Update HELM config

api-spec/aca-api.yaml
=> [PAGOPA-2128] fix: payStandIn default true

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
Changing path of gpd core api: we will use the newly created api `gpd for aca `
Needed in order to correctly add the service type when creating a new debt position
Manually
expected)
=> feat: using new api path gpd for aca PAGOPA-2196

README.md, aca-openapi.yaml
=> fix code-review

src/main/kotlin/it/pagopa/aca/services/AcaService.kt, src/test/kotlin/it/pagopa/aca/service/AcaServiceTests.kt
- adds a check to verify the existence of the paFiscalCode provided as input
Currently, the paCreatePosition call does not verify the existence of the paFiscalCode provided as input.
JUnit test
expected)
=> [PIDM-38] Add check for paFiscalCode

src/main/kotlin/it/pagopa/aca/client/IbansClient.kt, src/test/kotlin/it/pagopa/aca/client/IbansClientTest.kt
=> [PIDM-38] run :spotlessApply

helm/values-prod.yaml
=> chore: Update values-prod.yaml

aca-openapi.yaml, api-spec/aca-api.yaml
- Add 403 error case to openapi spec.
This PR aims to add the 403 status code in OpenAPI for the APIs under the authorizer because this type of error may occur when the authorizer blocks the client's request.
expected)
=> [PIDM-200] Add 403 to openapi spec.
